server {
    listen 80;
    server_name localhost;
    root /usr/share/nginx/html;
    index index.html;

    # Для SPA (React) - все запросы перенаправляем на index.html
    location / {
        try_files $uri $uri/ /index.html;
    }

    # Кэширование статических файлов
    location /static {
        expires 1y;
        add_header Cache-Control "public, immutable";
    }
}